name: task_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  firebase_database: ^8.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  fluttertoast: ^8.0.8
  intl: ^0.17.0
  ndialog: ^4.1.0
  share: ^2.0.4

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
